services:
  - type: web
    name: nasa-apod-explorer
    env: node
    rootDir: .
    buildCommand: |
      npm install -g vite
      cd frontend
      npm install
      npm run build
      cd ../backend
      npm install
    startCommand: node backend/server.js
    envVars:
      - key: NASA_API_KEY
        sync: false
